spring:
  application:
    name: devops-practice
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true