apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=   # base64 encoded value for "password"
  MYSQL_PASSWORD: bXlwYXNzd29yZA==     # base64 encoded value for "mypassword"