apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_USER: bXl1c2Vy  # base64 encoded value of 'myuser'
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value of 'password'