apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_USERNAME: bXl1c2Vy  # base64 encoded value of 'myuser'
  DB_PASSWORD: cGFzc3dvcmQ=  # base64 encoded value of 'password'